<a href="https://www.kaggle.com/code/tanyaarya19/digit-recognizer-2023?scriptVersionId=140925641" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
data = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')

In [3]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev/255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train/255.
_,m_train = X_train.shape

In [5]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10,1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(0, Z)

def softmax(Z):
    return (np.exp(Z)/sum(np.exp(Z)))

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def back_prop(Z1, A1, Z2, A2,W1, W2,X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1/m * dZ2.dot(A1.T)
    db1 = 1/m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * (Z1>0) #Derivative of ReLU
    dW1 = 1/m * dZ1.dot(X.T)
    db2 = 1/m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha*dW1
    b1 = b1 - alpha*db1
    W2 = W2 - alpha*dW2
    b2 = b2 - alpha*db2
    return W1, b1, W2, b2  

In [6]:
def get_predictions(A2):
    return np.argmax(A2,0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y)/Y.size

def gradient_descent(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2,W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ",i)
            predictions = get_predictions(A2)
            print("Accuracy: ",get_accuracy(predictions,Y))
    return W1, b1, W2, b2
    

In [7]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 500, 0.10)

Iteration:  0
[4 8 4 ... 4 4 0] [8 8 1 ... 9 1 7]
Accuracy:  0.099
Iteration:  10
[2 8 8 ... 2 2 0] [8 8 1 ... 9 1 7]
Accuracy:  0.16619512195121952
Iteration:  20
[2 2 8 ... 2 2 0] [8 8 1 ... 9 1 7]
Accuracy:  0.21609756097560975
Iteration:  30
[2 2 8 ... 4 2 0] [8 8 1 ... 9 1 7]
Accuracy:  0.2675609756097561
Iteration:  40
[2 2 8 ... 4 2 0] [8 8 1 ... 9 1 7]
Accuracy:  0.3258536585365854
Iteration:  50
[2 2 8 ... 4 2 0] [8 8 1 ... 9 1 7]
Accuracy:  0.3738292682926829
Iteration:  60
[2 2 8 ... 4 2 7] [8 8 1 ... 9 1 7]
Accuracy:  0.4225121951219512
Iteration:  70
[2 2 8 ... 4 8 7] [8 8 1 ... 9 1 7]
Accuracy:  0.4700243902439024
Iteration:  80
[2 2 1 ... 4 8 7] [8 8 1 ... 9 1 7]
Accuracy:  0.528390243902439
Iteration:  90
[2 2 1 ... 4 8 7] [8 8 1 ... 9 1 7]
Accuracy:  0.5847317073170731
Iteration:  100
[2 2 1 ... 4 1 7] [8 8 1 ... 9 1 7]
Accuracy:  0.6279024390243902
Iteration:  110
[2 3 1 ... 9 1 7] [8 8 1 ... 9 1 7]
Accuracy:  0.6577073170731708
Iteration:  120
[2 3 1 ... 9 1 7] [8 8 

85% accuracy

In [8]:
def make_predictions(X, W1, b1, W2, b2):
    _,_,_,A2 = forward_prop(W1,b1,W2,b2,X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = X_train[:,index,None]
    prediction = make_predictions(X_train[:,index,None],W1,b1,W2,b2)
    label = Y_train[index]
    print("Prediction: ", prediction)
    print("Label: ",label)
    
    current_image = current_image.reshape((28,28))
    plt.gray()
    plt.imshow(current_image, interpolation = 'nearest')
    plt.show()